CC-16026 Bugfix
spryker-eco/unzer pull request #14
Opened 2022-03-10 10:56 UTC by kkicheglovspryker

https://spryker.atlassian.net/browse/CC-16026

2022-03-10 11:11 UTC, AsonUnique approved these changes

2022-03-10 11:11 UTC, AsonUnique commented on src/SprykerEco/Zed/Unzer/Business/Credentials/UnzerCredentialsCreator.php
> +            $propelConnection->beginTransaction();
Shouldn't we start transactions outside of `try`/`catch`?

2022-03-10 11:11 UTC, AsonUnique commented on src/SprykerEco/Zed/Unzer/Business/Credentials/Validator/Constraints/TransferConstraint.php
> +     * {@inheritDoc}
redundant

2022-03-10 11:11 UTC, AsonUnique commented on src/SprykerEco/Zed/Unzer/Business/Credentials/Validator/Constraints/UnzerCredentialsConstraintsProviderInterface.php
> +     * @return array
Can we specify the array structure?

2022-03-10 15:42 UTC, michbeck approved these changes

2022-03-11 08:22 UTC, DmitryLymarenko requested changes

2022-03-11 08:22 UTC, DmitryLymarenko commented on src/SprykerEco/Zed/Unzer/Business/Credentials/Validator/Constraints/TransferConstraintValidator.php
> +    public function validate($value, Constraint $constraint): void
please avoid constraint usage at the business layer
we restrict such cases since they bring too much magic

2022-03-11 08:22 UTC, DmitryLymarenko commented on src/SprykerEco/Zed/Unzer/Business/Credentials/Validator/Constraints/UnzerCredentialsConstraintsProvider.php
> +    protected function getMarketplaceMainMerchantConstraintsCollection(): array
not a `collection` anymore

2022-03-11 08:22 UTC, DmitryLymarenko commented on src/SprykerEco/Zed/Unzer/Business/Credentials/Validator/Constraints/UnzerCredentialsConstraintsProvider.php
> +    protected function getMarketplaceMerchantConstraintsCollection(): array
the same

2022-03-15 11:02 UTC, DmitryLymarenko approved these changes
I disagree with Constraint solution at the business layer.
We have to avoid it.
This approval is just to unblock further processes under the responsibility of @floriankraemer and Jeremy.

2022-03-15 11:09 UTC, merged